/**
 * HackTrack | Synora'26 Demo Dataset
 * 2-Round Architecture (100 Marks Each, Total 200 Marks)
 */

const DEMO_DATA = {
  users: [
    {
      userId: "USR-ADM-01",
      name: "Super Administrator",
      email: "admin@synora.io",
      password: "admin",
      role: "admin",
      specialization: "System Administration & Jury Control",
      status: "active",
      createdAt: "2026-08-15 08:00:00"
    },
    {
      userId: "USR-ORG-01",
      name: "Alex Rivera",
      email: "organizer@synora.io",
      password: "admin",
      role: "organizer",
      specialization: "Operations & Registration Desk",
      status: "active",
      createdAt: "2026-08-15 08:30:00"
    },
    {
      userId: "USR-ORG-02",
      name: "Sarah Chen",
      email: "sarah.org@synora.io",
      password: "admin",
      role: "organizer",
      specialization: "Logistics & Stage Management",
      status: "active",
      createdAt: "2026-08-15 08:45:00"
    },
    {
      userId: "USR-JDG-01",
      name: "Prof. Alan Turing",
      email: "judge1@synora.io",
      password: "admin",
      role: "judge",
      specialization: "AI/ML & Deep Learning",
      status: "active",
      createdAt: "2026-08-15 09:00:00"
    },
    {
      userId: "USR-JDG-02",
      name: "Dr. Grace Hopper",
      email: "judge2@synora.io",
      password: "admin",
      role: "judge",
      specialization: "Cloud & Distributed Systems",
      status: "active",
      createdAt: "2026-08-15 09:15:00"
    },
    {
      userId: "USR-JDG-03",
      name: "Prof. Ada Lovelace",
      email: "judge3@synora.io",
      password: "admin",
      role: "judge",
      specialization: "Cyber Security & Cryptography",
      status: "active",
      createdAt: "2026-08-15 09:30:00"
    }
  ],

  teams: [
    {
      teamId: "HT2026001",
      teamName: "Neural Ninjas",
      projectTitle: "NeuroScan: Autonomous Multimodal Early Cancer Diagnostics",
      domain: "AI/ML",
      problemStatement: "PS-AI-01: Low-latency distributed cancer anomaly detection via edge vision transformers",
      college: "Stanford Institute of Technology",
      department: "Computer Science & Engineering",
      leaderName: "Marcus Vance",
      leaderEmail: "marcus.v@stanford.edu",
      leaderPhone: "+1 (555) 234-5678",
      member2Name: "Elena Rostova",
      member2Email: "elena.r@stanford.edu",
      member2Phone: "+1 (555) 234-5679",
      member3Name: "Kavya Patel",
      member3Email: "kavya.p@stanford.edu",
      member3Phone: "+1 (555) 234-5680",
      member4Name: "Liam O'Connor",
      member4Email: "liam.o@stanford.edu",
      member4Phone: "+1 (555) 234-5681",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026001-94821",
      createdAt: "2026-08-15 09:10:00"
    },
    {
      teamId: "HT2026002",
      teamName: "Cyber Sentinels",
      projectTitle: "ZeroTrust Mesh: Decentralized Quantum-Resistant Identity Gate",
      domain: "Cyber Security",
      problemStatement: "PS-CY-02: Post-quantum secure zero-trust identity authentication for microservices",
      college: "MIT College of Engineering",
      department: "Cyber Security & Forensics",
      leaderName: "David Sterling",
      leaderEmail: "david.s@mit.edu",
      leaderPhone: "+1 (555) 345-6789",
      member2Name: "Aaliyah Khan",
      member2Email: "aaliyah.k@mit.edu",
      member2Phone: "+1 (555) 345-6790",
      member3Name: "Carlos Mendez",
      member3Email: "carlos.m@mit.edu",
      member3Phone: "+1 (555) 345-6791",
      member4Name: "Zoe Washington",
      member4Email: "zoe.w@mit.edu",
      member4Phone: "+1 (555) 345-6792",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026002-38291",
      createdAt: "2026-08-15 09:18:00"
    },
    {
      teamId: "HT2026003",
      teamName: "Quantum Coders",
      projectTitle: "QubitFlow: Fault-Tolerant Quantum Algorithm Simulator for Logistics",
      domain: "Cryptography & Web3",
      problemStatement: "PS-Q-02: Near-term quantum approximate optimization for global supply chains",
      college: "UC Berkeley School of Computing",
      department: "Information Technology",
      leaderName: "Sophia Zhang",
      leaderEmail: "sophia.z@berkeley.edu",
      leaderPhone: "+1 (555) 456-7890",
      member2Name: "Aditya Sharma",
      member2Email: "aditya.s@berkeley.edu",
      member2Phone: "+1 (555) 456-7891",
      member3Name: "Nadia Rossi",
      member3Email: "nadia.r@berkeley.edu",
      member3Phone: "+1 (555) 456-7892",
      member4Name: "",
      member4Email: "",
      member4Phone: "",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026003-11029",
      createdAt: "2026-08-15 09:25:00"
    },
    {
      teamId: "HT2026004",
      teamName: "Web Wizards",
      projectTitle: "OmniCollab: Real-Time WebAssembly Collaborative Canvas & IDE",
      domain: "Web Development",
      problemStatement: "PS-WD-08: Ultra-low latency multi-tenant canvas rendering using CRDTs & WASM",
      college: "Carnegie Mellon University",
      department: "Computer Science",
      leaderName: "Ryan Cooper",
      leaderEmail: "ryan.c@cmu.edu",
      leaderPhone: "+1 (555) 567-8901",
      member2Name: "Priya Nair",
      member2Email: "priya.n@cmu.edu",
      member2Phone: "+1 (555) 567-8902",
      member3Name: "Tomasz Nowak",
      member3Email: "tomasz.n@cmu.edu",
      member3Phone: "+1 (555) 567-8903",
      member4Name: "Emily Watson",
      member4Email: "emily.w@cmu.edu",
      member4Phone: "+1 (555) 567-8904",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026004-77281",
      createdAt: "2026-08-15 09:32:00"
    },
    {
      teamId: "HT2026005",
      teamName: "Cloud Knights",
      projectTitle: "HyperScale Guardian: Autonomous Cost & Latency Balancer for K8s",
      domain: "Cloud & DevOps",
      problemStatement: "PS-CD-07: Multi-cloud automated micro-service migration and carbon-aware scheduling",
      college: "Georgia Tech",
      department: "Software Engineering",
      leaderName: "Ethan Bennett",
      leaderEmail: "ethan.b@gatech.edu",
      leaderPhone: "+1 (555) 678-9012",
      member2Name: "Fatima Al-Sayed",
      member2Email: "fatima.a@gatech.edu",
      member2Phone: "+1 (555) 678-9013",
      member3Name: "Lucas Silva",
      member3Email: "lucas.s@gatech.edu",
      member3Phone: "+1 (555) 678-9014",
      member4Name: "",
      member4Email: "",
      member4Phone: "",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026005-44910",
      createdAt: "2026-08-15 09:40:00"
    },
    {
      teamId: "HT2026006",
      teamName: "AI Pioneers",
      projectTitle: "BioSynthetica: Generative Diffusion Models for Therapeutic Peptide Design",
      domain: "AI/ML",
      problemStatement: "PS-AI-01: Generative molecular structure prediction with targeted binding affinity",
      college: "Harvard John A. Paulson SEAS",
      department: "Bio-Informatics & AI",
      leaderName: "Chloe Dupont",
      leaderEmail: "chloe.d@seas.harvard.edu",
      leaderPhone: "+1 (555) 789-0123",
      member2Name: "Kenji Sato",
      member2Email: "kenji.s@seas.harvard.edu",
      member2Phone: "+1 (555) 789-0124",
      member3Name: "Ananya Iyer",
      member3Email: "ananya.i@seas.harvard.edu",
      member3Phone: "+1 (555) 789-0125",
      member4Name: "Benjamin Lee",
      member4Email: "benjamin.l@seas.harvard.edu",
      member4Phone: "+1 (555) 789-0126",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026006-55928",
      createdAt: "2026-08-15 09:48:00"
    },
    {
      teamId: "HT2026007",
      teamName: "AgroPulse Tech",
      projectTitle: "AgriVision: Solar IoT Micro-Spectrometers for Autonomous Crop Health",
      domain: "Agriculture & ML",
      problemStatement: "PS-AG-03: Spectral imaging for nitrogen depletion detection in precision farming",
      college: "Texas A&M University",
      department: "Agricultural & Systems Engineering",
      leaderName: "Jackson Miller",
      leaderEmail: "jackson.m@tamu.edu",
      leaderPhone: "+1 (555) 890-1234",
      member2Name: "Mei Lin",
      member2Email: "mei.l@tamu.edu",
      member2Phone: "+1 (555) 890-1235",
      member3Name: "Devon Brooks",
      member3Email: "devon.b@tamu.edu",
      member3Phone: "+1 (555) 890-1236",
      member4Name: "",
      member4Email: "",
      member4Phone: "",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026007-88301",
      createdAt: "2026-08-15 09:55:00"
    },
    {
      teamId: "HT2026008",
      teamName: "HealthBlock Collective",
      projectTitle: "MediLedger: Zero-Knowledge Decentralized Clinical Trial Verification",
      domain: "Healthcare & Blockchain",
      problemStatement: "PS-HC-04: Privacy-preserving patient clinical trial data verification using zk-SNARKs",
      college: "Johns Hopkins University",
      department: "Biomedical Engineering",
      leaderName: "Hannah Abbott",
      leaderEmail: "hannah.a@jhu.edu",
      leaderPhone: "+1 (555) 901-2345",
      member2Name: "Rohan Gupta",
      member2Email: "rohan.g@jhu.edu",
      member2Phone: "+1 (555) 901-2346",
      member3Name: "Samuel Green",
      member3Email: "samuel.g@jhu.edu",
      member3Phone: "+1 (555) 901-2347",
      member4Name: "Clara Oswald",
      member4Email: "clara.o@jhu.edu",
      member4Phone: "+1 (555) 901-2348",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026008-99412",
      createdAt: "2026-08-15 10:02:00"
    },
    {
      teamId: "HT2026009",
      teamName: "Data Dynamos",
      projectTitle: "StreamNexus: Real-Time Fraud Mitigation on Financial WebSockets",
      domain: "FinTech & Open Banking",
      problemStatement: "PS-FT-05: Sub-millisecond graph neural network transaction anomaly filtering",
      college: "Columbia University",
      department: "Financial Engineering",
      leaderName: "Oliver Queen",
      leaderEmail: "oliver.q@columbia.edu",
      leaderPhone: "+1 (555) 012-3456",
      member2Name: "Jessica Jones",
      member2Email: "jessica.j@columbia.edu",
      member2Phone: "+1 (555) 012-3457",
      member3Name: "Barry Allen",
      member3Email: "barry.a@columbia.edu",
      member3Phone: "+1 (555) 012-3458",
      member4Name: "Diana Prince",
      member4Email: "diana.p@columbia.edu",
      member4Phone: "+1 (555) 012-3459",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026009-12490",
      createdAt: "2026-08-15 10:10:00"
    },
    {
      teamId: "HT2026010",
      teamName: "IoT Innovators",
      projectTitle: "GridMesh: Self-Healing LoRaWAN Microgrid Sensor Network",
      domain: "IoT & Smart Hardware",
      problemStatement: "PS-IOT-06: Resilient edge mesh topology for rural emergency electrical grids",
      college: "Purdue University",
      department: "Electrical & Computer Engineering",
      leaderName: "Peter Parker",
      leaderEmail: "peter.p@purdue.edu",
      leaderPhone: "+1 (555) 123-4567",
      member2Name: "Gwen Stacy",
      member2Email: "gwen.s@purdue.edu",
      member2Phone: "+1 (555) 123-4568",
      member3Name: "Miles Morales",
      member3Email: "miles.m@purdue.edu",
      member3Phone: "+1 (555) 123-4569",
      member4Name: "",
      member4Email: "",
      member4Phone: "",
      status: "present",
      locked: true,
      problemSubmitted: true,
      submissionLocked: true,
      qrCodeToken: "HT26-SEC-HT2026010-39201",
      createdAt: "2026-08-15 10:18:00"
    }
  ],

  attendance: [
    { attendanceId: "ATT-001", teamId: "HT2026001", teamName: "Neural Ninjas", status: "present", checkInTime: "2026-08-16 08:05:12", markedBy: "Alex Rivera" },
    { attendanceId: "ATT-002", teamId: "HT2026002", teamName: "Cyber Sentinels", status: "present", checkInTime: "2026-08-16 08:07:44", markedBy: "Alex Rivera" },
    { attendanceId: "ATT-003", teamId: "HT2026003", teamName: "Quantum Coders", status: "present", checkInTime: "2026-08-16 08:11:02", markedBy: "Sarah Chen" },
    { attendanceId: "ATT-004", teamId: "HT2026004", teamName: "Web Wizards", status: "present", checkInTime: "2026-08-16 08:14:55", markedBy: "Alex Rivera" },
    { attendanceId: "ATT-005", teamId: "HT2026005", teamName: "Cloud Knights", status: "present", checkInTime: "2026-08-16 08:16:30", markedBy: "Alex Rivera" },
    { attendanceId: "ATT-006", teamId: "HT2026006", teamName: "AI Pioneers", status: "present", checkInTime: "2026-08-16 08:18:19", markedBy: "Sarah Chen" },
    { attendanceId: "ATT-007", teamId: "HT2026007", teamName: "AgroPulse Tech", status: "present", checkInTime: "2026-08-16 08:22:40", markedBy: "Alex Rivera" },
    { attendanceId: "ATT-008", teamId: "HT2026008", teamName: "HealthBlock Collective", status: "present", checkInTime: "2026-08-16 08:25:11", markedBy: "Sarah Chen" },
    { attendanceId: "ATT-009", teamId: "HT2026009", teamName: "Data Dynamos", status: "present", checkInTime: "2026-08-16 08:28:50", markedBy: "Alex Rivera" },
    { attendanceId: "ATT-010", teamId: "HT2026010", teamName: "IoT Innovators", status: "present", checkInTime: "2026-08-16 08:31:05", markedBy: "Alex Rivera" }
  ],

  evaluations_r1: [
    { evalId: "EV1-01", judgeId: "USR-JDG-01", judgeName: "Prof. Alan Turing", teamId: "HT2026001", teamName: "Neural Ninjas", c1: 25, c2: 24, c3: 25, c4: 24, total: 98, comments: "Exceptional architecture with novel attention mechanisms for edge inference.", timestamp: "2026-08-16 10:15:00" },
    { evalId: "EV1-02", judgeId: "USR-JDG-02", judgeName: "Dr. Grace Hopper", teamId: "HT2026001", teamName: "Neural Ninjas", c1: 24, c2: 25, c3: 24, c4: 25, total: 97, comments: "Very clear problem framing and strong pitch.", timestamp: "2026-08-16 10:20:00" },
    { evalId: "EV1-03", judgeId: "USR-JDG-01", judgeName: "Prof. Alan Turing", teamId: "HT2026002", teamName: "Cyber Sentinels", c1: 24, c2: 24, c3: 23, c4: 24, total: 95, comments: "Solid quantum resistance cryptography plan.", timestamp: "2026-08-16 10:30:00" },
    { evalId: "EV1-04", judgeId: "USR-JDG-03", judgeName: "Prof. Ada Lovelace", teamId: "HT2026002", teamName: "Cyber Sentinels", c1: 25, c2: 24, c3: 24, c4: 24, total: 97, comments: "Impressive lattice cryptography conceptual foundation.", timestamp: "2026-08-16 10:35:00" },
    { evalId: "EV1-05", judgeId: "USR-JDG-02", judgeName: "Dr. Grace Hopper", teamId: "HT2026004", teamName: "Web Wizards", c1: 23, c2: 24, c3: 24, c4: 24, total: 95, comments: "Great WebAssembly compilation pipeline demonstration.", timestamp: "2026-08-16 10:45:00" }
  ],

  evaluations_r2: [
    { evalId: "EV2-01", judgeId: "USR-JDG-01", judgeName: "Prof. Alan Turing", teamId: "HT2026001", teamName: "Neural Ninjas", c1: 25, c2: 25, c3: 25, c4: 24, total: 99, comments: "Flawless prototype and real-time medical imaging demo.", timestamp: "2026-08-16 14:15:00" },
    { evalId: "EV2-02", judgeId: "USR-JDG-02", judgeName: "Dr. Grace Hopper", teamId: "HT2026001", teamName: "Neural Ninjas", c1: 24, c2: 25, c3: 24, c4: 25, total: 98, comments: "Clean microservices architecture with robust error boundaries.", timestamp: "2026-08-16 14:20:00" },
    { evalId: "EV2-03", judgeId: "USR-JDG-03", judgeName: "Prof. Ada Lovelace", teamId: "HT2026002", teamName: "Cyber Sentinels", c1: 24, c2: 24, c3: 24, c4: 24, total: 96, comments: "Kyber/Dilithium key exchange functioning smoothly.", timestamp: "2026-08-16 14:35:00" },
    { evalId: "EV2-04", judgeId: "USR-JDG-02", judgeName: "Dr. Grace Hopper", teamId: "HT2026004", teamName: "Web Wizards", c1: 23, c2: 24, c3: 23, c4: 24, total: 94, comments: "CRDT conflict resolution algorithm working in real-time.", timestamp: "2026-08-16 14:45:00" }
  ],

  roundConfig: [
    { roundId: "problem_statements", roundName: "Problem Statements Phase", description: "Release problem statements & unlock 1-time team portal submission", status: "active", maxMarks: 0 },
    { roundId: "round1", roundName: "Round 1 – Innovation & Pitch", description: "Ideation, research, pitch presentation and problem understanding", status: "active", maxMarks: 100 },
    { roundId: "round2", roundName: "Round 2 – Prototype & Working Demo", description: "Technical implementation, working prototype, functionality & scale", status: "active", maxMarks: 100 }
  ],

  settings: {
    eventName: "Synora'26",
    edition: "2026",
    isLeaderboardLocked: false,
    areWinnersDeclared: false,
    isCertificateSystemEnabled: true,
    organizerSignature: "Dr. Rachel Adams (Convener, Synora'26)",
    collegeLogoUrl: "assets/logo/synora-logo.png",
    round1Active: true,
    round2Active: true,
    problemStatementsReleased: true,
    lastWinnerLockTime: null
  },

  activityLogs: [
    { logId: "LOG-001", timestamp: "2026-08-15 08:00:00", userId: "USR-ADM-01", userName: "Super Administrator", role: "admin", action: "System Initialized", details: "HackTrack Synora'26 platform 2-round schema initialized." },
    { logId: "LOG-002", timestamp: "2026-08-15 08:30:00", userId: "USR-ADM-01", userName: "Super Administrator", role: "admin", action: "User Created", details: "Created Organizer Alex Rivera (organizer@synora.io)." },
    { logId: "LOG-003", timestamp: "2026-08-15 09:10:00", userId: "USR-ORG-01", userName: "Alex Rivera", role: "organizer", action: "Team Registered", details: "Registered team Neural Ninjas (HT2026001) with cryptographic QR pass." },
    { logId: "LOG-004", timestamp: "2026-08-16 08:00:00", userId: "USR-ADM-01", userName: "Super Administrator", role: "admin", action: "Workflow Update", details: "Problem Statements Phase toggled to ACTIVE. Team QR portals unlocked for submission." },
    { logId: "LOG-005", timestamp: "2026-08-16 08:05:12", userId: "USR-ORG-01", userName: "Alex Rivera", role: "organizer", action: "Attendance Check-in", details: "Checked in team Neural Ninjas (HT2026001) via QR scanner." },
    { logId: "LOG-006", timestamp: "2026-08-16 10:00:00", userId: "USR-ADM-01", userName: "Super Administrator", role: "admin", action: "Workflow Update", details: "Round 1 (Innovation & Pitch) opened for Jury Evaluation." },
    { logId: "LOG-007", timestamp: "2026-08-16 10:15:00", userId: "USR-JDG-01", userName: "Prof. Alan Turing", role: "judge", action: "Score Submitted", details: "Submitted Round 1 score (98/100) for Neural Ninjas (HT2026001)." },
    { logId: "LOG-008", timestamp: "2026-08-16 14:00:00", userId: "USR-ADM-01", userName: "Super Administrator", role: "admin", action: "Workflow Update", details: "Round 2 (Prototype & Demo) opened for Jury Evaluation." }
  ]
};

if (typeof window !== "undefined") {
  window.DEMO_DATA = DEMO_DATA;
}
